name: Tauri Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-tauri:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Вместо ubuntu-latest используем ubuntu-22.04
        os: [ ubuntu-22.04, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies for Linux
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libglib2.0-dev

      - name: Install dependencies
        run: npm install

      - name: Build Tauri
        run: npm run tauri build

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: tauri-bundle-${{ matrix.os }}
          path: src-tauri/target/release/bundle